#!/bin/sh
#
# Start the wpa_supplicant....
#

mkdir -p /run/network

case "$1" in
  start)
	printf "Starting wpa_supplicant.. "
	wpa_supplicant -B -i wlan0 -c /etc/default/SSID.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping wpa_supplicant.. "
	killall wpa_supplicant
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
